# SwiftLint Configuration for SnapChef
# Optimized for Swift 6 and SwiftUI development

# Paths to include/exclude
included:
  - SnapChef
excluded:
  - SnapChef.backup_20250802_180618
  - SnapChef.backup_20250802_180611
  - Pods
  - DerivedData
  - .build
  - agents

# Enabled rules beyond default set
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_assert
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # We use TODOs for development
  - trailing_comma # SwiftUI often benefits from trailing commas
  - multiple_closures_with_trailing_closure # SwiftUI uses this pattern
  - nesting # SwiftUI can have deep nesting
  - function_body_length # Some complex views need longer functions
  - type_body_length # Some models/views can be large
  - file_length # Some files are necessarily long
  - line_length # Long lines are sometimes needed

# Rule configurations
cyclomatic_complexity:
  warning: 15
  error: 20

force_cast:
  severity: warning

force_try:
  severity: warning

force_unwrapping:
  severity: warning

implicitly_unwrapped_optional:
  severity: warning


large_tuple:
  warning: 3
  error: 4

type_name:
  min_length: 3
  max_length: 50
  allowed_symbols: ["_"]

identifier_name:
  min_length: 1
  max_length: 50
  allowed_symbols: ["_"]
  validates_start_with_lowercase: warning
  excluded: ["x", "y", "i", "j", "k"]

function_parameter_count:
  warning: 8
  error: 10

# Custom rules for Swift 6 compliance
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: '^\s*print\('
    message: "Use proper logging instead of print statements"
    severity: warning

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, markdown, github-actions-logging)
reporter: "xcode"