import Foundation

struct LocalRecipeDatabase {
    static let shared = LocalRecipeDatabase()
    
    private init() {}
    
    // Helper function to create ingredients from strings
    private func createIngredients(from items: [String]) -> [Ingredient] {
        return items.map { item in
            Ingredient(id: UUID(), name: item, quantity: "", unit: nil, isAvailable: true)
        }
    }
    
    // Default nutrition for all recipes
    private let defaultNutrition = Nutrition(calories: 450, protein: 25, carbs: 35, fat: 18)
    
    // MARK: - Italian Recipes
    lazy var italianRecipes: [Recipe] = [
        Recipe(
            id: UUID(),
            name: "Classic Spaghetti Carbonara",
            description: "Creamy pasta with crispy pancetta and parmesan",
            ingredients: createIngredients(from: ["400g spaghetti", "200g pancetta", "4 egg yolks", "100g Parmigiano Reggiano", "Black pepper", "Salt"]),
            instructions: ["Cook spaghetti until al dente", "Crisp pancetta in a pan", "Mix egg yolks with cheese", "Toss hot pasta with pancetta", "Remove from heat and add egg mixture", "Season with pepper"],
            cookTime: 20,
            prepTime: 10,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Margherita Pizza",
            description: "Traditional Italian pizza with fresh mozzarella and basil",
            ingredients: createIngredients(from: ["Pizza dough", "200g mozzarella", "400g tomato sauce", "Fresh basil", "Olive oil", "Salt"]),
            instructions: ["Roll out pizza dough", "Spread tomato sauce", "Add torn mozzarella", "Bake at 250°C for 10 minutes", "Top with fresh basil", "Drizzle with olive oil"],
            cookTime: 15,
            prepTime: 20,
            servings: 2,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Risotto alla Milanese",
            description: "Creamy saffron risotto from Milan",
            ingredients: createIngredients(from: ["320g Arborio rice", "1L beef stock", "Saffron", "100g butter", "100g Parmigiano", "1 onion", "White wine"]),
            instructions: ["Sauté onion in butter", "Add rice and toast", "Add wine and let evaporate", "Add stock gradually", "Stir in saffron", "Finish with butter and cheese"],
            cookTime: 25,
            prepTime: 10,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Osso Buco",
            description: "Braised veal shanks in tomato sauce",
            ingredients: createIngredients(from: ["4 veal shanks", "2 carrots", "2 celery stalks", "1 onion", "400g tomatoes", "White wine", "Beef stock"]),
            instructions: ["Dust veal with flour", "Brown in hot oil", "Sauté vegetables", "Add wine and tomatoes", "Braise for 2 hours", "Serve with gremolata"],
            cookTime: 2,
            prepTime: 30,
            servings: 4,
            difficulty: .hard,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Panna Cotta",
            description: "Silky Italian dessert with vanilla",
            ingredients: createIngredients(from: ["500ml heavy cream", "100g sugar", "2 packets gelatin", "1 vanilla pod", "Berries for serving"]),
            instructions: ["Bloom gelatin in cold water", "Heat cream with sugar and vanilla", "Dissolve gelatin in warm cream", "Pour into molds", "Refrigerate 4 hours", "Serve with berries"],
            cookTime: 10,
            prepTime: 15,
            servings: 6,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Chicken Parmigiana",
            description: "Breaded chicken with tomato sauce and melted cheese",
            ingredients: createIngredients(from: ["4 chicken breasts", "200g breadcrumbs", "200g mozzarella", "400g tomato sauce", "100g Parmesan", "2 eggs"]),
            instructions: ["Pound chicken thin", "Dip in egg then breadcrumbs", "Fry until golden", "Top with sauce and cheese", "Bake until melted", "Serve hot"],
            cookTime: 30,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Minestrone Soup",
            description: "Hearty vegetable soup with pasta",
            ingredients: createIngredients(from: ["2 carrots", "2 celery", "1 onion", "400g tomatoes", "200g pasta", "Cannellini beans", "Vegetable stock"]),
            instructions: ["Dice all vegetables", "Sauté in olive oil", "Add stock and tomatoes", "Simmer 20 minutes", "Add pasta and beans", "Cook until tender"],
            cookTime: 30,
            prepTime: 15,
            servings: 6,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Tiramisu",
            description: "Classic coffee-flavored Italian dessert",
            ingredients: createIngredients(from: ["500g mascarpone", "6 egg yolks", "100g sugar", "300ml espresso", "Ladyfingers", "Cocoa powder", "Amaretto"]),
            instructions: ["Whisk yolks with sugar", "Fold in mascarpone", "Dip ladyfingers in coffee", "Layer with cream", "Refrigerate overnight", "Dust with cocoa"],
            cookTime: 0,
            prepTime: 30,
            servings: 8,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Caprese Salad",
            description: "Fresh tomato and mozzarella salad",
            ingredients: createIngredients(from: ["3 tomatoes", "250g fresh mozzarella", "Fresh basil", "Olive oil", "Balsamic vinegar", "Salt", "Pepper"]),
            instructions: ["Slice tomatoes and mozzarella", "Arrange alternately", "Tuck basil between slices", "Drizzle with oil", "Add balsamic", "Season to taste"],
            cookTime: 0,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Pasta Amatriciana",
            description: "Roman pasta with guanciale and tomato",
            ingredients: createIngredients(from: ["400g pasta", "150g guanciale", "400g tomatoes", "Pecorino Romano", "Red pepper flakes", "White wine"]),
            instructions: ["Crisp guanciale", "Add wine to deglaze", "Add tomatoes", "Simmer 15 minutes", "Toss with pasta", "Top with pecorino"],
            cookTime: 20,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Eggplant Parmigiana",
            description: "Layered eggplant with cheese and tomato",
            ingredients: createIngredients(from: ["2 eggplants", "400g tomato sauce", "250g mozzarella", "100g Parmesan", "Flour", "Olive oil"]),
            instructions: ["Slice eggplant", "Dredge in flour", "Fry until golden", "Layer with sauce and cheese", "Bake 30 minutes", "Let rest before serving"],
            cookTime: 45,
            prepTime: 30,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Focaccia Bread",
            description: "Italian flatbread with herbs",
            ingredients: createIngredients(from: ["500g flour", "7g yeast", "350ml water", "Olive oil", "Rosemary", "Cherry tomatoes", "Sea salt"]),
            instructions: ["Mix dough ingredients", "Let rise 2 hours", "Stretch in pan", "Dimple with fingers", "Top with oil and herbs", "Bake until golden"],
            cookTime: 25,
            prepTime: 3,
            servings: 8,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Pasta Aglio e Olio",
            description: "Simple garlic and olive oil pasta",
            ingredients: createIngredients(from: ["400g spaghetti", "6 garlic cloves", "100ml olive oil", "Red pepper flakes", "Parsley", "Parmesan"]),
            instructions: ["Cook pasta al dente", "Slice garlic thin", "Sauté in olive oil", "Add pepper flakes", "Toss with pasta", "Garnish with parsley"],
            cookTime: 15,
            prepTime: 5,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Saltimbocca alla Romana",
            description: "Veal with prosciutto and sage",
            ingredients: createIngredients(from: ["8 veal cutlets", "8 prosciutto slices", "Fresh sage", "White wine", "Butter", "Flour"]),
            instructions: ["Top veal with prosciutto and sage", "Secure with toothpick", "Dredge in flour", "Sauté in butter", "Deglaze with wine", "Serve immediately"],
            cookTime: 15,
            prepTime: 10,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Gnocchi with Gorgonzola",
            description: "Potato dumplings in creamy cheese sauce",
            ingredients: createIngredients(from: ["500g potato gnocchi", "200g gorgonzola", "200ml cream", "Walnuts", "Fresh sage", "Butter"]),
            instructions: ["Cook gnocchi until they float", "Melt gorgonzola in cream", "Toss gnocchi in sauce", "Add toasted walnuts", "Garnish with sage", "Serve hot"],
            cookTime: 15,
            prepTime: 5,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        )
    ]
    
    // MARK: - Mexican Recipes
    lazy var mexicanRecipes: [Recipe] = [
        Recipe(
            id: UUID(),
            name: "Chicken Tacos al Pastor",
            description: "Marinated chicken with pineapple and cilantro",
            ingredients: createIngredients(from: ["500g chicken thighs", "1 pineapple", "Corn tortillas", "Onion", "Cilantro", "Lime", "Achiote paste"]),
            instructions: ["Marinate chicken in achiote", "Grill with pineapple", "Chop chicken and pineapple", "Warm tortillas", "Fill with chicken", "Top with onion and cilantro"],
            cookTime: 20,
            prepTime: 2,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Guacamole",
            description: "Fresh avocado dip with lime",
            ingredients: createIngredients(from: ["3 avocados", "1 lime", "1 tomato", "1/2 onion", "1 jalapeño", "Cilantro", "Salt"]),
            instructions: ["Mash avocados", "Dice tomato and onion", "Mince jalapeño", "Mix all ingredients", "Add lime juice", "Season with salt"],
            cookTime: 0,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Enchiladas Verdes",
            description: "Chicken enchiladas with green salsa",
            ingredients: createIngredients(from: ["12 tortillas", "500g chicken", "Green salsa", "200g cheese", "Sour cream", "Onion", "Cilantro"]),
            instructions: ["Cook and shred chicken", "Dip tortillas in salsa", "Fill with chicken", "Roll and place in dish", "Top with salsa and cheese", "Bake until bubbly"],
            cookTime: 25,
            prepTime: 20,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Pozole Rojo",
            description: "Traditional hominy and pork soup",
            ingredients: createIngredients(from: ["1kg pork shoulder", "Hominy", "Dried chiles", "Garlic", "Onion", "Cabbage", "Radishes", "Lime"]),
            instructions: ["Simmer pork until tender", "Make chile sauce", "Add hominy to pork", "Simmer with sauce", "Serve with toppings", "Garnish with lime"],
            cookTime: 3,
            prepTime: 30,
            servings: 8,
            difficulty: .hard,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Churros",
            description: "Fried dough sticks with cinnamon sugar",
            ingredients: createIngredients(from: ["250ml water", "100g butter", "150g flour", "3 eggs", "Oil for frying", "Sugar", "Cinnamon"]),
            instructions: ["Boil water with butter", "Add flour all at once", "Beat in eggs", "Pipe into hot oil", "Fry until golden", "Roll in cinnamon sugar"],
            cookTime: 20,
            prepTime: 15,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Carne Asada",
            description: "Grilled marinated flank steak",
            ingredients: createIngredients(from: ["1kg flank steak", "Lime juice", "Orange juice", "Garlic", "Cilantro", "Cumin", "Tortillas"]),
            instructions: ["Marinate steak 4 hours", "Grill over high heat", "Let rest 5 minutes", "Slice against grain", "Serve with tortillas", "Add salsa and lime"],
            cookTime: 15,
            prepTime: 4,
            servings: 6,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Salsa Verde",
            description: "Tangy green tomatillo salsa",
            ingredients: createIngredients(from: ["500g tomatillos", "2 jalapeños", "4 garlic cloves", "1/2 onion", "Cilantro", "Lime", "Salt"]),
            instructions: ["Roast tomatillos", "Char jalapeños", "Blend with garlic", "Add onion and cilantro", "Season with lime", "Adjust salt"],
            cookTime: 15,
            prepTime: 10,
            servings: 6,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Quesadillas",
            description: "Cheese-filled grilled tortillas",
            ingredients: createIngredients(from: ["Flour tortillas", "300g cheese", "Mushrooms", "Poblano peppers", "Onion", "Butter"]),
            instructions: ["Sauté vegetables", "Place cheese on tortilla", "Add vegetables", "Fold tortilla", "Grill until crispy", "Cut into wedges"],
            cookTime: 10,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Mole Poblano",
            description: "Complex chocolate and chile sauce",
            ingredients: createIngredients(from: ["Various dried chiles", "Chocolate", "Almonds", "Raisins", "Spices", "Chicken", "Sesame seeds"]),
            instructions: ["Toast chiles and spices", "Blend with nuts", "Simmer with chocolate", "Cook until thick", "Serve over chicken", "Garnish with sesame"],
            cookTime: 2,
            prepTime: 45,
            servings: 8,
            difficulty: .hard,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Fish Tacos",
            description: "Beer-battered fish with cabbage slaw",
            ingredients: createIngredients(from: ["White fish", "Beer batter", "Cabbage", "Mayo", "Lime", "Corn tortillas", "Hot sauce"]),
            instructions: ["Make beer batter", "Fry fish until crispy", "Make cabbage slaw", "Warm tortillas", "Assemble tacos", "Drizzle with sauce"],
            cookTime: 20,
            prepTime: 15,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Chilaquiles",
            description: "Breakfast tortilla chips in salsa",
            ingredients: createIngredients(from: ["Tortilla chips", "Red salsa", "Eggs", "Cheese", "Crema", "Onion", "Cilantro"]),
            instructions: ["Heat salsa in pan", "Add tortilla chips", "Toss to coat", "Top with fried eggs", "Add cheese and crema", "Garnish with onion"],
            cookTime: 15,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Tamales",
            description: "Steamed corn masa with filling",
            ingredients: createIngredients(from: ["Masa harina", "Lard", "Corn husks", "Chicken", "Red sauce", "Baking powder"]),
            instructions: ["Soak corn husks", "Beat lard until fluffy", "Mix with masa", "Spread on husks", "Add filling", "Steam 60 minutes"],
            cookTime: 60,
            prepTime: 2,
            servings: 12,
            difficulty: .hard,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Elote",
            description: "Mexican street corn",
            ingredients: createIngredients(from: ["4 corn cobs", "Mayo", "Cotija cheese", "Chili powder", "Lime", "Butter"]),
            instructions: ["Grill corn", "Brush with mayo", "Roll in cheese", "Sprinkle chili powder", "Squeeze lime", "Serve on stick"],
            cookTime: 15,
            prepTime: 5,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Carnitas",
            description: "Slow-cooked crispy pork",
            ingredients: createIngredients(from: ["2kg pork shoulder", "Orange", "Bay leaves", "Cinnamon", "Lard", "Salt"]),
            instructions: ["Cut pork in chunks", "Simmer in lard", "Add orange and spices", "Cook 3 hours", "Crisp under broiler", "Shred and serve"],
            cookTime: 3,
            prepTime: 15,
            servings: 8,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Flan",
            description: "Caramel custard dessert",
            ingredients: createIngredients(from: ["1 cup sugar", "6 eggs", "1 can evaporated milk", "1 can condensed milk", "Vanilla"]),
            instructions: ["Make caramel", "Pour in mold", "Blend eggs and milk", "Pour over caramel", "Bake in water bath", "Chill overnight"],
            cookTime: 60,
            prepTime: 15,
            servings: 8,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        )
    ]
    
    // MARK: - Chinese Recipes
    lazy var chineseRecipes: [Recipe] = [
        Recipe(
            id: UUID(),
            name: "Kung Pao Chicken",
            description: "Spicy chicken with peanuts and peppers",
            ingredients: createIngredients(from: ["500g chicken", "Peanuts", "Dried chilies", "Sichuan pepper", "Soy sauce", "Rice wine", "Bell peppers"]),
            instructions: ["Marinate chicken", "Stir-fry chilies", "Add chicken", "Toss with vegetables", "Add sauce", "Garnish with peanuts"],
            cookTime: 15,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Fried Rice",
            description: "Classic egg fried rice with vegetables",
            ingredients: createIngredients(from: ["3 cups cooked rice", "3 eggs", "Peas", "Carrots", "Green onions", "Soy sauce", "Sesame oil"]),
            instructions: ["Scramble eggs", "Stir-fry vegetables", "Add cold rice", "Break up clumps", "Season with soy sauce", "Finish with sesame oil"],
            cookTime: 10,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Mapo Tofu",
            description: "Spicy tofu in meat sauce",
            ingredients: createIngredients(from: ["Soft tofu", "200g ground pork", "Doubanjiang", "Sichuan pepper", "Green onions", "Garlic", "Ginger"]),
            instructions: ["Brown ground pork", "Add doubanjiang", "Add stock", "Gently add tofu", "Simmer 5 minutes", "Top with green onions"],
            cookTime: 15,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Peking Duck",
            description: "Crispy roasted duck with pancakes",
            ingredients: createIngredients(from: ["1 whole duck", "Maltose", "5-spice", "Pancakes", "Cucumber", "Green onions", "Hoisin sauce"]),
            instructions: ["Air-dry duck overnight", "Glaze with maltose", "Roast at high heat", "Carve skin and meat", "Serve with pancakes", "Add condiments"],
            cookTime: 2,
            prepTime: 24,
            servings: 4,
            difficulty: .hard,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Spring Rolls",
            description: "Crispy vegetable-filled appetizers",
            ingredients: createIngredients(from: ["Spring roll wrappers", "Cabbage", "Carrots", "Bean sprouts", "Mushrooms", "Soy sauce", "Oil"]),
            instructions: ["Julienne vegetables", "Stir-fry briefly", "Cool completely", "Wrap tightly", "Deep fry until golden", "Serve with sauce"],
            cookTime: 20,
            prepTime: 30,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Sweet and Sour Pork",
            description: "Crispy pork in tangy sauce",
            ingredients: createIngredients(from: ["500g pork", "Pineapple", "Bell peppers", "Vinegar", "Sugar", "Ketchup", "Cornstarch"]),
            instructions: ["Coat pork in batter", "Deep fry until crispy", "Make sweet-sour sauce", "Stir-fry vegetables", "Toss pork in sauce", "Serve immediately"],
            cookTime: 25,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Dumplings",
            description: "Pork and vegetable filled dumplings",
            ingredients: createIngredients(from: ["Dumpling wrappers", "300g ground pork", "Napa cabbage", "Ginger", "Soy sauce", "Sesame oil"]),
            instructions: ["Mix filling ingredients", "Place in wrappers", "Pleat and seal", "Steam or pan-fry", "Make dipping sauce", "Serve hot"],
            cookTime: 15,
            prepTime: 45,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Chow Mein",
            description: "Stir-fried noodles with vegetables",
            ingredients: createIngredients(from: ["Fresh noodles", "Chicken", "Bean sprouts", "Carrots", "Cabbage", "Soy sauce", "Oyster sauce"]),
            instructions: ["Boil noodles briefly", "Stir-fry chicken", "Add vegetables", "Toss in noodles", "Add sauces", "Serve hot"],
            cookTime: 15,
            prepTime: 15,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Beef and Broccoli",
            description: "Tender beef with crisp broccoli",
            ingredients: createIngredients(from: ["500g beef", "Broccoli", "Garlic", "Ginger", "Soy sauce", "Oyster sauce", "Cornstarch"]),
            instructions: ["Marinate beef", "Blanch broccoli", "Stir-fry beef", "Add aromatics", "Toss with broccoli", "Thicken sauce"],
            cookTime: 15,
            prepTime: 20,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Hot and Sour Soup",
            description: "Tangy soup with tofu and mushrooms",
            ingredients: createIngredients(from: ["Tofu", "Mushrooms", "Eggs", "Vinegar", "White pepper", "Soy sauce", "Cornstarch"]),
            instructions: ["Simmer stock", "Add mushrooms", "Add tofu", "Season with vinegar", "Drizzle beaten eggs", "Thicken with starch"],
            cookTime: 20,
            prepTime: 15,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Char Siu",
            description: "Cantonese BBQ pork",
            ingredients: createIngredients(from: ["1kg pork shoulder", "Hoisin sauce", "Honey", "5-spice", "Red food coloring", "Soy sauce"]),
            instructions: ["Marinate pork overnight", "Roast at high heat", "Baste frequently", "Caramelize edges", "Rest before slicing", "Serve with rice"],
            cookTime: 45,
            prepTime: 24,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Dan Dan Noodles",
            description: "Sichuan noodles with spicy meat sauce",
            ingredients: createIngredients(from: ["Fresh noodles", "Ground pork", "Sesame paste", "Sichuan pepper", "Chili oil", "Green onions"]),
            instructions: ["Cook noodles", "Brown pork", "Mix sauce ingredients", "Toss noodles in sauce", "Top with pork", "Garnish with onions"],
            cookTime: 15,
            prepTime: 10,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Egg Drop Soup",
            description: "Silky egg ribbons in clear broth",
            ingredients: createIngredients(from: ["Chicken broth", "3 eggs", "Cornstarch", "Green onions", "White pepper", "Sesame oil"]),
            instructions: ["Heat broth", "Beat eggs", "Thicken broth slightly", "Drizzle eggs while stirring", "Season to taste", "Garnish with onions"],
            cookTime: 10,
            prepTime: 5,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "General Tso's Chicken",
            description: "Crispy chicken in sweet spicy sauce",
            ingredients: createIngredients(from: ["600g chicken", "Cornstarch", "Soy sauce", "Rice vinegar", "Sugar", "Dried chilies", "Garlic"]),
            instructions: ["Batter chicken", "Deep fry until crispy", "Make sauce", "Stir-fry aromatics", "Toss chicken in sauce", "Garnish with onions"],
            cookTime: 25,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Wontons",
            description: "Delicate pork dumplings in soup",
            ingredients: createIngredients(from: ["Wonton wrappers", "250g ground pork", "Shrimp", "Green onions", "Ginger", "Chicken broth"]),
            instructions: ["Mix filling", "Wrap wontons", "Boil in water", "Heat broth", "Add wontons to broth", "Garnish with onions"],
            cookTime: 15,
            prepTime: 30,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        )
    ]
    
    // MARK: - Japanese Recipes
    lazy var japaneseRecipes: [Recipe] = [
        Recipe(
            id: UUID(),
            name: "Chicken Teriyaki",
            description: "Glazed chicken with sweet soy sauce",
            ingredients: createIngredients(from: ["4 chicken thighs", "Soy sauce", "Mirin", "Sugar", "Sake", "Ginger", "Green onions"]),
            instructions: ["Score chicken skin", "Pan-fry skin down", "Flip and cook through", "Make teriyaki sauce", "Glaze chicken", "Garnish with onions"],
            cookTime: 20,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Sushi Rolls",
            description: "California and tuna rolls",
            ingredients: createIngredients(from: ["Sushi rice", "Nori", "Tuna", "Cucumber", "Avocado", "Crab", "Rice vinegar"]),
            instructions: ["Season sushi rice", "Place nori on mat", "Spread rice evenly", "Add fillings", "Roll tightly", "Cut into pieces"],
            cookTime: 0,
            prepTime: 45,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Ramen",
            description: "Rich pork broth noodle soup",
            ingredients: createIngredients(from: ["Ramen noodles", "Pork bones", "Chashu pork", "Soft eggs", "Green onions", "Nori", "Bamboo"]),
            instructions: ["Simmer bones 12 hours", "Cook chashu pork", "Prepare toppings", "Cook noodles", "Assemble bowls", "Serve immediately"],
            cookTime: 12,
            prepTime: 2,
            servings: 4,
            difficulty: .hard,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Tempura",
            description: "Light crispy battered vegetables and shrimp",
            ingredients: createIngredients(from: ["Shrimp", "Vegetables", "Flour", "Ice water", "Egg", "Oil", "Dipping sauce"]),
            instructions: ["Make cold batter", "Heat oil to 170°C", "Dip and fry items", "Drain on paper", "Serve immediately", "With dipping sauce"],
            cookTime: 20,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Miso Soup",
            description: "Traditional soybean paste soup",
            ingredients: createIngredients(from: ["Dashi stock", "Miso paste", "Tofu", "Wakame seaweed", "Green onions"]),
            instructions: ["Heat dashi stock", "Dissolve miso paste", "Add cubed tofu", "Add wakame", "Garnish with onions", "Serve hot"],
            cookTime: 10,
            prepTime: 5,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Yakitori",
            description: "Grilled chicken skewers",
            ingredients: createIngredients(from: ["Chicken thighs", "Green onions", "Soy sauce", "Mirin", "Sugar", "Sake", "Bamboo skewers"]),
            instructions: ["Cut chicken in pieces", "Thread on skewers", "Make tare sauce", "Grill over charcoal", "Brush with sauce", "Turn frequently"],
            cookTime: 15,
            prepTime: 20,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Gyoza",
            description: "Pan-fried pork dumplings",
            ingredients: createIngredients(from: ["Gyoza wrappers", "Ground pork", "Cabbage", "Garlic", "Ginger", "Soy sauce", "Sesame oil"]),
            instructions: ["Mix filling", "Wrap gyoza", "Pan-fry bottoms", "Add water and cover", "Steam until cooked", "Serve with sauce"],
            cookTime: 15,
            prepTime: 30,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Katsu Curry",
            description: "Breaded pork with Japanese curry",
            ingredients: createIngredients(from: ["Pork cutlets", "Panko", "Curry roux", "Potatoes", "Carrots", "Onions", "Rice"]),
            instructions: ["Bread pork cutlets", "Deep fry until golden", "Make curry sauce", "Simmer vegetables", "Slice katsu", "Serve over rice"],
            cookTime: 30,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Okonomiyaki",
            description: "Savory Japanese pancake",
            ingredients: createIngredients(from: ["Flour", "Eggs", "Cabbage", "Bacon", "Okonomiyaki sauce", "Mayo", "Bonito flakes"]),
            instructions: ["Mix batter", "Add shredded cabbage", "Cook like pancake", "Top with bacon", "Flip and cook", "Add toppings"],
            cookTime: 15,
            prepTime: 15,
            servings: 2,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Udon Soup",
            description: "Thick noodles in savory broth",
            ingredients: createIngredients(from: ["Udon noodles", "Dashi", "Soy sauce", "Mirin", "Tempura", "Green onions", "Kamaboko"]),
            instructions: ["Make dashi broth", "Season broth", "Cook udon noodles", "Prepare toppings", "Assemble bowls", "Serve hot"],
            cookTime: 15,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Donburi",
            description: "Chicken and egg rice bowl",
            ingredients: createIngredients(from: ["Chicken thighs", "Eggs", "Onions", "Dashi", "Soy sauce", "Mirin", "Rice"]),
            instructions: ["Simmer chicken", "Add onions", "Pour sauce over", "Beat eggs lightly", "Pour over chicken", "Serve on rice"],
            cookTime: 20,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Takoyaki",
            description: "Octopus balls",
            ingredients: createIngredients(from: ["Octopus", "Flour", "Eggs", "Dashi", "Green onions", "Pickled ginger", "Takoyaki sauce"]),
            instructions: ["Make batter", "Heat takoyaki pan", "Pour batter", "Add octopus pieces", "Turn with picks", "Top with sauce"],
            cookTime: 15,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Chirashi Bowl",
            description: "Assorted sashimi over rice",
            ingredients: createIngredients(from: ["Sushi rice", "Assorted sashimi", "Cucumber", "Avocado", "Shiso leaves", "Wasabi", "Soy sauce"]),
            instructions: ["Prepare sushi rice", "Slice sashimi", "Arrange over rice", "Add vegetables", "Garnish with shiso", "Serve with wasabi"],
            cookTime: 0,
            prepTime: 30,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Karaage",
            description: "Japanese fried chicken",
            ingredients: createIngredients(from: ["Chicken thighs", "Soy sauce", "Sake", "Ginger", "Garlic", "Potato starch", "Oil"]),
            instructions: ["Marinate chicken", "Coat in starch", "Deep fry twice", "First at 160°C", "Then at 180°C", "Serve with lemon"],
            cookTime: 20,
            prepTime: 30,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Matcha Ice Cream",
            description: "Green tea flavored dessert",
            ingredients: createIngredients(from: ["Heavy cream", "Milk", "Sugar", "Matcha powder", "Egg yolks"]),
            instructions: ["Heat milk and cream", "Whisk yolks with sugar", "Temper with hot milk", "Add matcha", "Chill completely", "Churn in machine"],
            cookTime: 30,
            prepTime: 4,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        )
    ]
    
    // Continue with Thai, Indian, French, and American recipes...
    // Due to length constraints, I'll implement the recipe selection logic
    
    func getRandomRecipe(for cuisine: String) -> Recipe? {
        let cleanCuisine = cuisine.replacingOccurrences(of: " 🍝", with: "")
            .replacingOccurrences(of: " 🌮", with: "")
            .replacingOccurrences(of: " 🥟", with: "")
            .replacingOccurrences(of: " 🍱", with: "")
            .replacingOccurrences(of: " 🍜", with: "")
            .replacingOccurrences(of: " 🍛", with: "")
            .replacingOccurrences(of: " 🥐", with: "")
            .replacingOccurrences(of: " 🍔", with: "")
        
        switch cleanCuisine.lowercased() {
        case "italian":
            return italianRecipes.randomElement()
        case "mexican":
            return mexicanRecipes.randomElement()
        case "chinese":
            return chineseRecipes.randomElement()
        case "japanese":
            return japaneseRecipes.randomElement()
        case "thai":
            return thaiRecipes.randomElement()
        case "indian":
            return indianRecipes.randomElement()
        case "french":
            return frenchRecipes.randomElement()
        case "american":
            return americanRecipes.randomElement()
        default:
            // Return a random recipe from any cuisine
            let allRecipes = italianRecipes + mexicanRecipes + chineseRecipes + japaneseRecipes
            return allRecipes.randomElement()
        }
    }
    
    // MARK: - Thai Recipes
    lazy var thaiRecipes: [Recipe] = [
        Recipe(
            id: UUID(),
            name: "Pad Thai",
            description: "Stir-fried rice noodles with tamarind",
            ingredients: createIngredients(from: ["Rice noodles", "Shrimp", "Tofu", "Bean sprouts", "Peanuts", "Tamarind", "Fish sauce"]),
            instructions: ["Soak noodles", "Make pad thai sauce", "Stir-fry shrimp", "Add noodles and sauce", "Toss with vegetables", "Top with peanuts"],
            cookTime: 15,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Green Curry",
            description: "Spicy coconut curry with vegetables",
            ingredients: createIngredients(from: ["Green curry paste", "Coconut milk", "Chicken", "Thai eggplant", "Basil", "Fish sauce"]),
            instructions: ["Fry curry paste", "Add coconut milk", "Simmer chicken", "Add vegetables", "Season to taste", "Garnish with basil"],
            cookTime: 25,
            prepTime: 15,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Tom Yum Soup",
            description: "Hot and sour shrimp soup",
            ingredients: createIngredients(from: ["Shrimp", "Lemongrass", "Galangal", "Lime leaves", "Chili", "Mushrooms", "Lime juice"]),
            instructions: ["Simmer aromatics", "Add mushrooms", "Cook shrimp", "Season with lime", "Add chili paste", "Garnish with cilantro"],
            cookTime: 20,
            prepTime: 15,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Massaman Curry",
            description: "Mild curry with peanuts and potatoes",
            ingredients: createIngredients(from: ["Beef", "Massaman paste", "Coconut milk", "Potatoes", "Peanuts", "Tamarind"]),
            instructions: ["Brown beef", "Fry curry paste", "Add coconut milk", "Simmer with potatoes", "Add peanuts", "Balance flavors"],
            cookTime: 2,
            prepTime: 20,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Som Tam",
            description: "Green papaya salad",
            ingredients: createIngredients(from: ["Green papaya", "Tomatoes", "Long beans", "Peanuts", "Dried shrimp", "Fish sauce", "Lime"]),
            instructions: ["Shred papaya", "Pound garlic and chili", "Add beans and tomatoes", "Mix with papaya", "Season dressing", "Toss together"],
            cookTime: 0,
            prepTime: 20,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Pad See Ew",
            description: "Stir-fried flat noodles with soy sauce",
            ingredients: createIngredients(from: ["Flat rice noodles", "Pork", "Chinese broccoli", "Eggs", "Dark soy sauce", "Sugar"]),
            instructions: ["Heat wok very hot", "Stir-fry pork", "Add noodles", "Push aside for eggs", "Add vegetables", "Toss with sauce"],
            cookTime: 10,
            prepTime: 15,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Larb",
            description: "Spicy meat salad",
            ingredients: createIngredients(from: ["Ground pork", "Mint", "Cilantro", "Shallots", "Lime juice", "Fish sauce", "Roasted rice powder"]),
            instructions: ["Cook pork", "Cool slightly", "Mix with herbs", "Add lime dressing", "Sprinkle rice powder", "Serve with vegetables"],
            cookTime: 10,
            prepTime: 15,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Thai Fried Rice",
            description: "Fragrant fried rice with basil",
            ingredients: createIngredients(from: ["Jasmine rice", "Chicken", "Thai basil", "Chili", "Fish sauce", "Eggs", "Garlic"]),
            instructions: ["Use cold rice", "Stir-fry chicken", "Add garlic and chili", "Toss in rice", "Season with sauce", "Finish with basil"],
            cookTime: 10,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Mango Sticky Rice",
            description: "Sweet coconut rice with mango",
            ingredients: createIngredients(from: ["Glutinous rice", "Coconut milk", "Sugar", "Salt", "Ripe mango", "Mung beans"]),
            instructions: ["Steam sticky rice", "Make coconut sauce", "Mix with rice", "Slice mango", "Arrange on plate", "Drizzle with sauce"],
            cookTime: 30,
            prepTime: 4,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Red Curry",
            description: "Spicy curry with bamboo shoots",
            ingredients: createIngredients(from: ["Red curry paste", "Coconut milk", "Beef", "Bamboo shoots", "Thai basil", "Fish sauce"]),
            instructions: ["Fry curry paste", "Add thick coconut milk", "Cook beef", "Add vegetables", "Simmer until tender", "Garnish with basil"],
            cookTime: 30,
            prepTime: 15,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Tom Kha Gai",
            description: "Coconut chicken soup",
            ingredients: createIngredients(from: ["Chicken", "Coconut milk", "Galangal", "Lemongrass", "Mushrooms", "Lime juice", "Chili oil"]),
            instructions: ["Simmer coconut milk", "Add aromatics", "Cook chicken", "Add mushrooms", "Season with lime", "Garnish with cilantro"],
            cookTime: 20,
            prepTime: 15,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Pad Kra Pao",
            description: "Thai basil stir-fry",
            ingredients: createIngredients(from: ["Ground pork", "Holy basil", "Garlic", "Chili", "Fish sauce", "Soy sauce", "Eggs"]),
            instructions: ["Stir-fry garlic and chili", "Add ground pork", "Season with sauces", "Add holy basil", "Fry eggs separately", "Serve over rice"],
            cookTime: 10,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Satay",
            description: "Grilled meat skewers with peanut sauce",
            ingredients: createIngredients(from: ["Chicken", "Turmeric", "Lemongrass", "Peanut butter", "Coconut milk", "Tamarind"]),
            instructions: ["Marinate chicken", "Thread on skewers", "Make peanut sauce", "Grill skewers", "Brush with marinade", "Serve with sauce"],
            cookTime: 15,
            prepTime: 2,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Thai Fish Cakes",
            description: "Spicy fish patties with cucumber relish",
            ingredients: createIngredients(from: ["White fish", "Red curry paste", "Green beans", "Lime leaves", "Fish sauce", "Cucumber"]),
            instructions: ["Blend fish smooth", "Mix with curry paste", "Add beans and herbs", "Form into patties", "Deep fry golden", "Serve with relish"],
            cookTime: 20,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Khao Soi",
            description: "Northern Thai curry noodle soup",
            ingredients: createIngredients(from: ["Egg noodles", "Chicken", "Curry paste", "Coconut milk", "Shallots", "Lime"]),
            instructions: ["Make curry base", "Simmer chicken", "Cook noodles", "Fry noodle garnish", "Assemble bowls", "Top with crispy noodles"],
            cookTime: 45,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        )
    ]
    
    // MARK: - Indian Recipes
    lazy var indianRecipes: [Recipe] = [
        Recipe(
            id: UUID(),
            name: "Chicken Tikka Masala",
            description: "Creamy tomato curry with grilled chicken",
            ingredients: createIngredients(from: ["Chicken", "Yogurt", "Tomatoes", "Cream", "Garam masala", "Ginger", "Garlic"]),
            instructions: ["Marinate chicken", "Grill until charred", "Make curry sauce", "Simmer chicken in sauce", "Finish with cream", "Garnish with cilantro"],
            cookTime: 30,
            prepTime: 2,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Palak Paneer",
            description: "Spinach curry with cottage cheese",
            ingredients: createIngredients(from: ["Spinach", "Paneer", "Onions", "Tomatoes", "Cream", "Cumin", "Garlic"]),
            instructions: ["Blanch spinach", "Blend to puree", "Sauté aromatics", "Add spinach puree", "Fold in paneer", "Finish with cream"],
            cookTime: 25,
            prepTime: 15,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Biryani",
            description: "Layered rice with spiced meat",
            ingredients: createIngredients(from: ["Basmati rice", "Lamb", "Yogurt", "Onions", "Saffron", "Whole spices", "Mint"]),
            instructions: ["Marinate meat", "Fry onions golden", "Parboil rice", "Layer meat and rice", "Steam covered", "Garnish with onions"],
            cookTime: 1,
            prepTime: 45,
            servings: 6,
            difficulty: .hard,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Dal Makhani",
            description: "Creamy black lentils",
            ingredients: createIngredients(from: ["Black lentils", "Kidney beans", "Butter", "Cream", "Tomatoes", "Ginger", "Garlic"]),
            instructions: ["Soak lentils overnight", "Pressure cook", "Make tomato base", "Simmer together", "Add butter and cream", "Cook until creamy"],
            cookTime: 2,
            prepTime: 8,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Samosas",
            description: "Crispy triangular pastries",
            ingredients: createIngredients(from: ["Flour", "Potatoes", "Peas", "Cumin", "Coriander seeds", "Ginger", "Oil"]),
            instructions: ["Make dough", "Cook potato filling", "Roll and cut dough", "Fill and fold", "Deep fry golden", "Serve with chutney"],
            cookTime: 30,
            prepTime: 45,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Butter Chicken",
            description: "Mild creamy chicken curry",
            ingredients: createIngredients(from: ["Chicken", "Butter", "Tomatoes", "Cream", "Fenugreek", "Ginger", "Garlic"]),
            instructions: ["Marinate chicken", "Grill or bake", "Make makhani sauce", "Simmer chicken", "Finish with butter", "Garnish with cream"],
            cookTime: 30,
            prepTime: 30,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Chole Bhature",
            description: "Chickpea curry with fried bread",
            ingredients: createIngredients(from: ["Chickpeas", "Onions", "Tomatoes", "Tea bags", "Flour", "Yogurt", "Spices"]),
            instructions: ["Soak chickpeas", "Make spiced curry", "Prepare bhature dough", "Let dough rest", "Deep fry bhature", "Serve together"],
            cookTime: 45,
            prepTime: 8,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Dosa",
            description: "Crispy fermented crepes",
            ingredients: createIngredients(from: ["Rice", "Urad dal", "Fenugreek seeds", "Salt", "Oil", "Water"]),
            instructions: ["Soak rice and dal", "Grind to batter", "Ferment overnight", "Spread thin on griddle", "Cook until crispy", "Serve with chutney"],
            cookTime: 20,
            prepTime: 24,
            servings: 6,
            difficulty: .hard,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Rogan Josh",
            description: "Kashmiri lamb curry",
            ingredients: createIngredients(from: ["Lamb", "Yogurt", "Kashmiri chilies", "Fennel", "Ginger", "Cinnamon", "Cardamom"]),
            instructions: ["Brown lamb pieces", "Cook aromatics", "Add yogurt slowly", "Simmer covered", "Add spice paste", "Cook until tender"],
            cookTime: 1,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Idli",
            description: "Steamed rice cakes",
            ingredients: createIngredients(from: ["Rice", "Urad dal", "Salt", "Water"]),
            instructions: ["Soak ingredients", "Grind separately", "Mix and ferment", "Pour in molds", "Steam 10 minutes", "Serve with sambar"],
            cookTime: 15,
            prepTime: 24,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Tandoori Chicken",
            description: "Clay oven roasted chicken",
            ingredients: createIngredients(from: ["Chicken", "Yogurt", "Tandoori masala", "Lemon juice", "Ginger", "Garlic", "Red color"]),
            instructions: ["Make cuts in chicken", "Marinate overnight", "Preheat oven high", "Roast on rack", "Baste with butter", "Char under broiler"],
            cookTime: 30,
            prepTime: 8,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Aloo Gobi",
            description: "Potato and cauliflower curry",
            ingredients: createIngredients(from: ["Potatoes", "Cauliflower", "Turmeric", "Cumin", "Tomatoes", "Ginger", "Peas"]),
            instructions: ["Cut vegetables", "Sauté spices", "Add potatoes first", "Then cauliflower", "Cook covered", "Garnish with cilantro"],
            cookTime: 25,
            prepTime: 15,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Gulab Jamun",
            description: "Sweet milk dumplings in syrup",
            ingredients: createIngredients(from: ["Milk powder", "Flour", "Baking soda", "Milk", "Sugar", "Cardamom", "Rose water"]),
            instructions: ["Make sugar syrup", "Mix dough", "Form small balls", "Deep fry golden", "Soak in syrup", "Serve warm"],
            cookTime: 30,
            prepTime: 20,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Paneer Tikka",
            description: "Grilled marinated cottage cheese",
            ingredients: createIngredients(from: ["Paneer", "Bell peppers", "Onions", "Yogurt", "Tikka masala", "Lemon"]),
            instructions: ["Cube paneer and vegetables", "Marinate 2 hours", "Thread on skewers", "Grill or bake", "Baste with butter", "Serve with chutney"],
            cookTime: 20,
            prepTime: 2,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Kheer",
            description: "Rice pudding with cardamom",
            ingredients: createIngredients(from: ["Basmati rice", "Milk", "Sugar", "Cardamom", "Almonds", "Pistachios", "Saffron"]),
            instructions: ["Boil milk", "Add rice", "Simmer stirring", "Reduce by half", "Add sugar and nuts", "Flavor with cardamom"],
            cookTime: 45,
            prepTime: 10,
            servings: 6,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        )
    ]
    
    // MARK: - French Recipes
    lazy var frenchRecipes: [Recipe] = [
        Recipe(
            id: UUID(),
            name: "Coq au Vin",
            description: "Chicken braised in red wine",
            ingredients: createIngredients(from: ["Chicken", "Red wine", "Bacon", "Mushrooms", "Pearl onions", "Thyme", "Bay leaves"]),
            instructions: ["Brown chicken pieces", "Cook bacon and vegetables", "Flambé with cognac", "Add wine and herbs", "Braise until tender", "Reduce sauce"],
            cookTime: 1,
            prepTime: 30,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Beef Bourguignon",
            description: "Beef stew with wine and vegetables",
            ingredients: createIngredients(from: ["Beef chuck", "Red wine", "Carrots", "Onions", "Mushrooms", "Bacon", "Tomato paste"]),
            instructions: ["Brown beef cubes", "Sauté vegetables", "Add wine and stock", "Braise 2 hours", "Add mushrooms", "Thicken sauce"],
            cookTime: 2,
            prepTime: 45,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Ratatouille",
            description: "Provençal vegetable stew",
            ingredients: createIngredients(from: ["Eggplant", "Zucchini", "Bell peppers", "Tomatoes", "Onions", "Herbs de Provence", "Olive oil"]),
            instructions: ["Slice vegetables", "Sauté separately", "Layer in dish", "Season each layer", "Bake covered", "Serve hot or cold"],
            cookTime: 45,
            prepTime: 30,
            servings: 6,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Croissants",
            description: "Buttery flaky pastries",
            ingredients: createIngredients(from: ["Flour", "Butter", "Milk", "Yeast", "Sugar", "Salt", "Egg"]),
            instructions: ["Make dough", "Laminate with butter", "Fold and chill", "Roll and cut", "Shape crescents", "Proof and bake"],
            cookTime: 20,
            prepTime: 12,
            servings: 12,
            difficulty: .hard,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Quiche Lorraine",
            description: "Bacon and cheese tart",
            ingredients: createIngredients(from: ["Pie crust", "Bacon", "Gruyère", "Eggs", "Heavy cream", "Nutmeg"]),
            instructions: ["Blind bake crust", "Cook bacon crispy", "Mix custard", "Add bacon and cheese", "Pour in crust", "Bake until set"],
            cookTime: 35,
            prepTime: 20,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Crème Brûlée",
            description: "Vanilla custard with caramelized sugar",
            ingredients: createIngredients(from: ["Heavy cream", "Egg yolks", "Sugar", "Vanilla bean", "Additional sugar for top"]),
            instructions: ["Infuse cream with vanilla", "Whisk yolks with sugar", "Temper and strain", "Bake in water bath", "Chill completely", "Torch sugar on top"],
            cookTime: 40,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "French Onion Soup",
            description: "Caramelized onion soup with cheese",
            ingredients: createIngredients(from: ["Onions", "Butter", "Beef stock", "White wine", "Baguette", "Gruyère cheese", "Thyme"]),
            instructions: ["Caramelize onions slowly", "Deglaze with wine", "Add stock and simmer", "Toast baguette slices", "Top with cheese", "Broil until bubbly"],
            cookTime: 1,
            prepTime: 15,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Duck à l'Orange",
            description: "Roasted duck with orange sauce",
            ingredients: createIngredients(from: ["Duck", "Oranges", "Sugar", "Wine vinegar", "Stock", "Grand Marnier"]),
            instructions: ["Score duck skin", "Roast breast down", "Make orange sauce", "Caramelize sugar", "Add juice and stock", "Slice and sauce"],
            cookTime: 1,
            prepTime: 20,
            servings: 4,
            difficulty: .hard,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Bouillabaisse",
            description: "Provençal fish stew",
            ingredients: createIngredients(from: ["Mixed fish", "Fennel", "Tomatoes", "Saffron", "Pastis", "Rouille", "Bread"]),
            instructions: ["Make fish stock", "Sauté vegetables", "Add tomatoes and herbs", "Simmer fish", "Make rouille", "Serve with toast"],
            cookTime: 45,
            prepTime: 30,
            servings: 6,
            difficulty: .hard,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Crêpes Suzette",
            description: "Thin pancakes with orange butter",
            ingredients: createIngredients(from: ["Flour", "Eggs", "Milk", "Butter", "Orange juice", "Grand Marnier", "Sugar"]),
            instructions: ["Make crêpe batter", "Cook thin crêpes", "Make orange butter", "Fold crêpes", "Flambé with liqueur", "Serve immediately"],
            cookTime: 30,
            prepTime: 30,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Cassoulet",
            description: "Bean stew with duck and sausage",
            ingredients: createIngredients(from: ["White beans", "Duck confit", "Pork shoulder", "Sausage", "Tomatoes", "Breadcrumbs"]),
            instructions: ["Soak beans overnight", "Cook meats separately", "Layer in cassole", "Add bean liquid", "Top with crumbs", "Bake slowly"],
            cookTime: 3,
            prepTime: 12,
            servings: 8,
            difficulty: .hard,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Niçoise Salad",
            description: "Tuna salad from Nice",
            ingredients: createIngredients(from: ["Tuna", "Eggs", "Anchovies", "Olives", "Tomatoes", "Green beans", "Olive oil"]),
            instructions: ["Cook eggs and beans", "Arrange on platter", "Add tuna and anchovies", "Scatter olives", "Drizzle olive oil", "Season simply"],
            cookTime: 15,
            prepTime: 15,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Madeleines",
            description: "Shell-shaped sponge cakes",
            ingredients: createIngredients(from: ["Flour", "Eggs", "Sugar", "Butter", "Lemon zest", "Baking powder"]),
            instructions: ["Melt butter", "Beat eggs and sugar", "Fold in flour", "Add butter and zest", "Chill batter", "Bake in molds"],
            cookTime: 12,
            prepTime: 2,
            servings: 24,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Boeuf Tartare",
            description: "Raw beef with seasonings",
            ingredients: createIngredients(from: ["Beef tenderloin", "Capers", "Shallots", "Egg yolk", "Mustard", "Worcestershire"]),
            instructions: ["Hand chop beef", "Mix seasonings", "Form patties", "Top with yolk", "Serve with toast", "Mix at table"],
            cookTime: 0,
            prepTime: 20,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Tarte Tatin",
            description: "Upside-down caramelized apple tart",
            ingredients: createIngredients(from: ["Apples", "Sugar", "Butter", "Puff pastry", "Vanilla", "Lemon"]),
            instructions: ["Caramelize sugar", "Arrange apples", "Cook until tender", "Cover with pastry", "Bake until golden", "Invert while warm"],
            cookTime: 40,
            prepTime: 20,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        )
    ]
    
    // MARK: - American Recipes
    lazy var americanRecipes: [Recipe] = [
        Recipe(
            id: UUID(),
            name: "BBQ Ribs",
            description: "Slow-cooked pork ribs with smoky sauce",
            ingredients: createIngredients(from: ["Pork ribs", "BBQ rub", "BBQ sauce", "Apple cider vinegar", "Brown sugar", "Paprika"]),
            instructions: ["Remove membrane", "Apply dry rub", "Smoke low and slow", "Wrap in foil", "Glaze with sauce", "Caramelize on grill"],
            cookTime: 4,
            prepTime: 20,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Classic Burger",
            description: "Juicy beef burger with all the fixings",
            ingredients: createIngredients(from: ["Ground beef", "Burger buns", "Cheese", "Lettuce", "Tomato", "Onion", "Pickles"]),
            instructions: ["Form patties", "Season simply", "Grill to medium", "Melt cheese", "Toast buns", "Assemble with toppings"],
            cookTime: 10,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Mac and Cheese",
            description: "Creamy baked macaroni and cheese",
            ingredients: createIngredients(from: ["Elbow macaroni", "Cheddar", "Butter", "Flour", "Milk", "Breadcrumbs"]),
            instructions: ["Cook pasta", "Make cheese sauce", "Combine pasta and sauce", "Top with crumbs", "Bake until bubbly", "Let rest 5 min"],
            cookTime: 30,
            prepTime: 15,
            servings: 6,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Fried Chicken",
            description: "Crispy buttermilk fried chicken",
            ingredients: createIngredients(from: ["Chicken pieces", "Buttermilk", "Flour", "Paprika", "Cayenne", "Oil"]),
            instructions: ["Marinate in buttermilk", "Season flour", "Double dredge", "Fry at 350°F", "Drain on rack", "Season while hot"],
            cookTime: 20,
            prepTime: 4,
            servings: 4,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Apple Pie",
            description: "Classic American apple pie",
            ingredients: createIngredients(from: ["Apples", "Pie crust", "Sugar", "Cinnamon", "Butter", "Lemon juice", "Egg wash"]),
            instructions: ["Peel and slice apples", "Mix with sugar and spice", "Fill bottom crust", "Dot with butter", "Cover and vent", "Bake until golden"],
            cookTime: 55,
            prepTime: 30,
            servings: 8,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Buffalo Wings",
            description: "Spicy chicken wings with blue cheese",
            ingredients: createIngredients(from: ["Chicken wings", "Hot sauce", "Butter", "Blue cheese", "Celery", "Ranch dressing"]),
            instructions: ["Fry wings crispy", "Melt butter with sauce", "Toss wings in sauce", "Serve immediately", "Side of blue cheese", "Celery sticks"],
            cookTime: 15,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Clam Chowder",
            description: "New England style creamy soup",
            ingredients: createIngredients(from: ["Clams", "Potatoes", "Bacon", "Onions", "Celery", "Heavy cream", "Thyme"]),
            instructions: ["Cook bacon crispy", "Sauté vegetables", "Add clam juice", "Simmer potatoes", "Add clams and cream", "Season to taste"],
            cookTime: 30,
            prepTime: 20,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Pancakes",
            description: "Fluffy buttermilk pancakes",
            ingredients: createIngredients(from: ["Flour", "Buttermilk", "Eggs", "Baking powder", "Butter", "Maple syrup"]),
            instructions: ["Mix dry ingredients", "Whisk wet separately", "Combine gently", "Cook on griddle", "Flip when bubbly", "Serve with syrup"],
            cookTime: 15,
            prepTime: 10,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Pulled Pork",
            description: "Slow-cooked shredded pork sandwich",
            ingredients: createIngredients(from: ["Pork shoulder", "Dry rub", "BBQ sauce", "Buns", "Coleslaw", "Pickles"]),
            instructions: ["Rub pork overnight", "Smoke 12 hours", "Wrap and rest", "Pull apart", "Mix with sauce", "Serve on buns"],
            cookTime: 12,
            prepTime: 30,
            servings: 8,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Chocolate Chip Cookies",
            description: "Classic chewy cookies",
            ingredients: createIngredients(from: ["Butter", "Brown sugar", "Eggs", "Flour", "Chocolate chips", "Vanilla"]),
            instructions: ["Cream butter and sugar", "Add eggs and vanilla", "Mix in flour", "Fold in chips", "Chill dough", "Bake until edges brown"],
            cookTime: 12,
            prepTime: 20,
            servings: 24,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Philly Cheesesteak",
            description: "Sliced steak sandwich with cheese",
            ingredients: createIngredients(from: ["Ribeye", "Hoagie rolls", "Provolone", "Onions", "Bell peppers", "Oil"]),
            instructions: ["Freeze and slice meat", "Sauté peppers and onions", "Cook meat quickly", "Melt cheese on top", "Fill rolls", "Serve immediately"],
            cookTime: 10,
            prepTime: 15,
            servings: 4,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Cornbread",
            description: "Sweet and savory corn bread",
            ingredients: createIngredients(from: ["Cornmeal", "Flour", "Sugar", "Buttermilk", "Eggs", "Butter", "Baking powder"]),
            instructions: ["Heat cast iron pan", "Mix dry ingredients", "Whisk wet ingredients", "Combine quickly", "Pour in hot pan", "Bake until golden"],
            cookTime: 25,
            prepTime: 10,
            servings: 8,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Jambalaya",
            description: "Louisiana rice with sausage and shrimp",
            ingredients: createIngredients(from: ["Andouille sausage", "Shrimp", "Chicken", "Rice", "Bell peppers", "Celery", "Cajun spice"]),
            instructions: ["Brown sausage", "Cook chicken", "Sauté trinity", "Add rice and stock", "Simmer covered", "Add shrimp last"],
            cookTime: 35,
            prepTime: 20,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Key Lime Pie",
            description: "Tart citrus pie from Florida",
            ingredients: createIngredients(from: ["Key lime juice", "Condensed milk", "Egg yolks", "Graham crackers", "Butter", "Whipped cream"]),
            instructions: ["Make graham crust", "Mix filling ingredients", "Pour in crust", "Bake briefly", "Chill completely", "Top with cream"],
            cookTime: 15,
            prepTime: 20,
            servings: 8,
            difficulty: .easy,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        ),
        Recipe(
            id: UUID(),
            name: "Biscuits and Gravy",
            description: "Fluffy biscuits with sausage gravy",
            ingredients: createIngredients(from: ["Flour", "Butter", "Buttermilk", "Breakfast sausage", "Milk", "Black pepper"]),
            instructions: ["Make biscuit dough", "Cut and bake", "Brown sausage", "Make milk gravy", "Season heavily", "Pour over biscuits"],
            cookTime: 25,
            prepTime: 15,
            servings: 6,
            difficulty: .medium,
            nutrition: defaultNutrition,
            imageURL: nil,
            createdAt: Date()
        )
    ]
}